### ISSUE TITLE
Amigo por amigo

### ISSUE THREAD

**Issue by NestorPlasencia** [jtavara23/reto3BackEnd#1]
En controllers/main.js 

//Requerimiento de modelo amigo
var amigo = require('../models/amigo');

Poner mayuscula  a Amigo, ya que al crear la instancia esta con mayuscula

var amigo = new Amigo({
        nombres: nombres,
        apellidos: apellidos
});

El resto corre genial :D Felicitaciones !!

**Comment by jtavara23** [comment]
Gracias Nestor
